{{- if .Values.extraIngressPaths.enabled -}}
{{- range .Values.extraIngressPaths.paths }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    {{- include "microservice.labels" $. | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ index $.Values.service.ports 0 }.port }}
      targetPort: {{ if $.Values.service.portName }}{{ $.Values.service.portName }}{{ else }}{{ index $.Values.service.ports 0 }.name }}{{ end }}
      protocol: TCP
      name: {{ if $.Values.service.portName }}{{ $.Values.service.portName }}{{ else }}{{ index $.Values.service.ports 0 }.name }}{{ end }}
  selector:
    {{- include "microservice.selectorLabels" $. | nindent 4 }}
---
{{- end }}
{{- end }}
