{{- if .Values.customAutoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "microservice.fullname" . }}
  minReplicas: {{ .Values.customAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.customAutoscaling.maxReplicas }}
  metrics:
    {{- if .Values.customAutoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.customAutoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.customAutoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.customAutoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
