{{- if and .Values.pdb.enabled (gt .Values.replicaCount  1.0)  -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
{{- end -}}
