{{- if (.Values.sealedSecret.enabled) -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "microservice.fullname" . }}-sealedsecret
  {{- with .Values.sealedSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.sealedSecret.encryptedData }}
  encryptedData:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    type: Opaque
    metadata:
      labels:
        {{- include "microservice.labels" . | nindent 8 }}
      {{- with .Values.sealedSecret.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
