replicaCount: 2

# Pod disruption budget will be created only if replicaCount > 1
pdb:
  enabled: true
  minAvailable: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 10

livenessProbe:
  enabled: true
  initialDelaySeconds: 10

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Allows you to add any config files in specified mount path
configFiles:
  config.yml: |
    key: value
  example.json: |
    {
      "key1": "value1",
      "key2": "value2"
    }

configFilesMountPath: /usr/share/config
