name: Lint and validate chart

on: pull_request

jobs:
  cancel-previous:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  helm-check:
    runs-on: ubuntu-latest
    needs: [cancel-previous]
    steps:
    - uses: actions/checkout@v4
    - name: helm-check-default
      uses: igabaydulin/helm-check-action@0.2.0
      env:
        CHART_LOCATION: ./
        CHART_VALUES: ./values.yaml
    - name: helm-check-test
      uses: igabaydulin/helm-check-action@0.2.0
      env:
        CHART_LOCATION: ./
        CHART_VALUES: ./ci/test-values.yaml
  
  test-k8s:
    runs-on: ubuntu-latest
    needs: [helm-check]
    strategy:
      matrix:
        k8s-version: [ v1.27.12, v1.26.15 ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.10.3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
        with:
          version: v3.10.1

      - name: Create Kind cluster
        uses: helm/kind-action@v1.9.0
        with:
          kubectl_version: ${{ matrix.k8s-version }}

      - name: Run chart-testing (install)
        run: ct install --config ci/config.yaml
