name: Lint and validate chart

on: pull_request

jobs:
  cancel-previous:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  helm-check:
    runs-on: ubuntu-latest
    needs: [cancel-previous]
    steps:
    - uses: actions/checkout@v4
    - name: helm-check
      uses: igabaydulin/helm-check-action@0.2.0
      env:
        CHART_LOCATION: ./
        CHART_VALUES: ./values.yaml
